spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: switcher
    password: switcher
  flyway:
    table: FLYWAY_SCHEMA_HISTORY
    baseline-on-migrate: true
logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: TRACE
